project:
  type: website
  output-dir: docs

website:
  title: "Home"
  favicon: logo.png
  navbar:
    background: dark
    left:
      - href: about.qmd
        text: About
      - href: research/index.qmd
        text: Research
      - href: cv.pdf
        text: CV
      - href: contact.qmd
        text: Contact  

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor:
  render-on-save: true
