---
title: "Heterogeneous UIPDs Across Firms: Spillovers from U.S. Monetary Policy Shocks."
author: 
  - Acosta-Henao, M.
  - Amado, M. A.
  - Marti, M.
  - Perez-Reyna, D. 
date: "2025"
---

We examine the granular transmission of U.S. monetary policy shocks to deviations from uncov-
ered interest rate parity (UIPDs) in emerging economies. Using data from Chile that accounts
for firm-bank relationships and time-variant firm and bank characteristics, we find that: (1)
Federal funds rate (FFR) shocks increase banks’ foreign borrowing costs; (2) these higher costs
disproportionately affect small firms, raising their UIPDs more than large firms; (3) this size-
differentiated impact arises from higher interest rates in domestic currency faced by small firms;
(4) in contrast, interest rates on dollar loans respond uniformly across firms; (5) no differential
effect is observed on loan quantities, indicating an active role of credit supply and demand. A
small open economy model of corporate default and heterogeneous firms, borrowing in different
currencies, rationalizes these findings. In the model, higher FFR reduces the cost of default
relative to repayment more for small than large firms.